version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    user: root
    privileged: true
    ports:
      - "8080:8080" # Порт для доступа к веб-интерфейсу Jenkins
      - "50000:50000" # Порт для связи агентов Jenkins
    volumes:
      - E:\javaProject\jkin-api\jenkinsdata:/var/jenkins_home
#    environment:
#      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - jenkins_network

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - E:\javaProject\jkin-api\sq\data:/opt/sonarqube/data
      - E:\javaProject\jkin-api\sq\logs:/opt/sonarqube/logs
      - E:\javaProject\jkin-api\sq\ext:/opt/sonarqube/extensions
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    networks:
      - jenkins_network

networks:
  jenkins_network:
    driver: bridge