version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    user: root
    privileged: true
    ports:
      - "8080:8080" # Порт для доступа к веб-интерфейсу Jenkins
      - "50000:50000" # Порт для связи агентов Jenkins
    volumes:
      - .\jenkinsdata:/var/jenkins_home
#    environment:
#      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - jenkins_network

  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - .\nexusdata:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=2g
    networks:
      - jenkins_network

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - .\sq\data:/opt/sonarqube/data
      - .\sq\logs:/opt/sonarqube/logs
      - .\sq\ext:/opt/sonarqube/extensions
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    networks:
      - jenkins_network

networks:
  jenkins_network:
    driver: bridge
