version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080" # Порт для доступа к веб-интерфейсу Jenkins
      - "50000:50000" # Порт для связи агентов Jenkins
    volumes:
      - E:\javaProject\jkin-api\jenkinsdata:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - jenkins_network

networks:
  jenkins_network:
    driver: bridge